# -*- coding: utf-8 -*-
"""Taller-Refuerzo-clase5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Kf0-RZ_5Nm9-5ACOb7fTDz8J_XTMbl2l

# Ejercicios

1. Crear un bucle que cuente todos los números pares hasta
el 100 ciclo for
"""

for i in range(2,101,2):
   print(i,end=(" "))

"""2. Haz una tabla de multiplicar utilizando el ciclo for
ciclo for
"""

Num= int(input("Ingrese el numero de la tabla de multiplicar a consultar: "))
for i in range(1,11):
  print(f"{Num} x {i} = {i*Num}")

"""3. Escribir un programa que pregunte al usuario su edad y
muestre por pantalla todos los años que ha cumplido
(desde 1 hasta su edad). ciclo for
"""

E_usuario= int(input("Digite su edad: "))
for u in range(E_usuario):
  print(str(u+1) +" Año(s)")

"""4. Escribir un programa que pida al usuario un número entero
positivo y muestre por pantalla todos los números
impares desde 1 hasta ese número separados por comas.
"""

digito= int(input("Ingrese un numero entero: "))
for D in range(1,digito+1,2):
  print(D,end=",")

"""5. Encuentra la suma de todos los números pares del 1 al
100 ciclo for
"""

suma=0
for R in range(100):
  if R % 2 == 0:
    print(R,end=(" "))
    suma= suma+R
print("\n La suma de numeros pares es: ",suma)